# Generated by Django 3.2.18 on 2023-02-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20230226_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(max_length=1024, upload_to='recipes_images/', verbose_name='Картинка'),
        ),
    ]
